Fix exception in _parse_srv_result_nt() (on Windows)
Sometimes 'result' parameter is byte[] which causes exception:
TypeError: 'str' does not support the buffer interface